name: Deploy Astro with pnpm

on:
  push:
    branches:
      - master # Or your desired deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write # Granting the id-token: write permission
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build Astro
        uses: withastro/action@v3
        with:
          node-version: 22 # Or your desired Node.js version
          package-manager: pnpm # Explicitly set pnpm
          build-command: pnpm run build # Or your custom build command

  deploy:
    needs: build # Ensures build job completes successfully
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
